//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurTRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurTRPO_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurTRPO_Accounts()
        {
            this.CurTRPO_Users = new HashSet<CurTRPO_Users>();
        }
    
        public int Id { get; set; }
        public int Role_Id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual CurTRPO_Role CurTRPO_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurTRPO_Users> CurTRPO_Users { get; set; }
    }
}
