//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurTRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurTRPO_Trips
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Shed_Id { get; set; }
        public string number_of_tickets { get; set; }
        public decimal total_price { get; set; }
    
        public virtual CurTRPO_Shedule CurTRPO_Shedule { get; set; }
        public virtual CurTRPO_Users CurTRPO_Users { get; set; }
    }
}
