//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurTRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurTRPO_Shedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurTRPO_Shedule()
        {
            this.CurTRPO_Trips = new HashSet<CurTRPO_Trips>();
        }
    
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Ship_Id { get; set; }
        public int Departure_Point_Id { get; set; }
        public Nullable<int> First_Stop_Id { get; set; }
        public Nullable<int> Second_Stop_Id { get; set; }
        public int Arrival_Point_Id { get; set; }
        public int Status_Id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public System.TimeSpan arrival_time { get; set; }
        public Nullable<decimal> price { get; set; }
        public string total_number_of_tickets { get; set; }
    
        public virtual CurTRPO_Ports CurTRPO_Ports { get; set; }
        public virtual CurTRPO_Ports CurTRPO_Ports1 { get; set; }
        public virtual CurTRPO_Ports CurTRPO_Ports2 { get; set; }
        public virtual CurTRPO_Ports CurTRPO_Ports3 { get; set; }
        public virtual CurTRPO_Ships CurTRPO_Ships { get; set; }
        public virtual CurTRPO_Status CurTRPO_Status { get; set; }
        public virtual CurTRPO_Users CurTRPO_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurTRPO_Trips> CurTRPO_Trips { get; set; }
    }
}
