//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurTRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurTRPO_Ships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurTRPO_Ships()
        {
            this.CurTRPO_Shedule = new HashSet<CurTRPO_Shedule>();
        }
    
        public int Id { get; set; }
        public int Ship_Type_Id { get; set; }
        public string name { get; set; }
        public string number_of_seats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurTRPO_Shedule> CurTRPO_Shedule { get; set; }
        public virtual CurTRPO_Ship_Type CurTRPO_Ship_Type { get; set; }
    }
}
