//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurTRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurTRPO_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurTRPO_Users()
        {
            this.CurTRPO_Shedule = new HashSet<CurTRPO_Shedule>();
            this.CurTRPO_Trips = new HashSet<CurTRPO_Trips>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string phone_number { get; set; }
    
        public virtual CurTRPO_Accounts CurTRPO_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurTRPO_Shedule> CurTRPO_Shedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurTRPO_Trips> CurTRPO_Trips { get; set; }
    }
}
