//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurTRPO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr691_baoEntities : DbContext
    {
        public gr691_baoEntities()
            : base("name=gr691_baoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurTRPO_Accounts> CurTRPO_Accounts { get; set; }
        public virtual DbSet<CurTRPO_Ports> CurTRPO_Ports { get; set; }
        public virtual DbSet<CurTRPO_Role> CurTRPO_Role { get; set; }
        public virtual DbSet<CurTRPO_Shedule> CurTRPO_Shedule { get; set; }
        public virtual DbSet<CurTRPO_Ship_Type> CurTRPO_Ship_Type { get; set; }
        public virtual DbSet<CurTRPO_Ships> CurTRPO_Ships { get; set; }
        public virtual DbSet<CurTRPO_Status> CurTRPO_Status { get; set; }
        public virtual DbSet<CurTRPO_Trips> CurTRPO_Trips { get; set; }
        public virtual DbSet<CurTRPO_Users> CurTRPO_Users { get; set; }
    }
}
